spring:
  profiles:
    active: dev
  application:
    name: angelcloud-consul
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: angelcloud-consul

server:
  port: 8501

